----
Total log time:			3978.760978	(100%) 0.00mA
Total suspend time:		0.00	(0.00%)
Total Active time:
	Total display on time:		902.49	(22.68%) 0.00mA
	Total display off (active) time:3076.27	(77.32%) 0.00mA
	Total USB connected time:	0.00	(0.00%)
	Total CPU1 up time:		0.00	(0.00%)


	Wakeup Sources Ordered By Count
		________________________________________________________________________________________________
		name			count			duration(seconds)	cost(mAh)		
		________________________________________________________________________________________________

	Freezing Abort Reasons Ordered By Count
		________________________________________________________________________________________________
		name			count			duration(seconds)	cost(mAh)		
		________________________________________________________________________________________________

	Device Failure Reasons Ordered By Count
		________________________________________________________________________________________________
		name			count			duration(seconds)	cost(mAh)		
		________________________________________________________________________________________________

	Longest Wakelocks Ordered By Duration
		________________________________________________________________________
		name			count			duration(seconds)	
		________________________________________________________________________

